name: Ask a Question
description: Ask us a question
title: "[Question]: "
labels: [question, triage]
assignees:
  - tgwolf
body:
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Please give us time to review your question and formulate an answer.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
