blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: Show your support
    url: https://ko-fi.com/wolfsoftware
    about: Show your support
