blank_issues_enabled: false
contact_links:
  - name: Supoport Us
    url: https://ko-fi.com/wolfsoftware
    about: Show your support.
  - name: Visit Wolf Software
    url: https://wolfsoftware.com
    about: Visit the Wolf Software website and see what else we do and what services we offer.
