blank_issues_enabled: false
contact_links:
  - name: Show your support
    url: https://ko-fi.com/wolfsoftware
    about: Show your support
  - name: Visit the Wolf Software website
    url: https://wolfsoftware.com
    about: stuff
